### PR TITLE
Add image build for s390x architecture

### PR DESCRIPTION
**Pull request by vitt-bagal**
Added changes for s390x image.

### CODE REVIEW

**Comment by deniszh** [comment]
LGTM, thanks!

**Comment by vitt-bagal** [comment]
@deniszh Thanks. Is it possible to retrigger `Build Release` action for current version `1.1.7-9` ?

**Comment by deniszh** [comment]
@vitt-bagal : Releases are atomic and immutable, but I can release 1.1.7-10

**Comment by vitt-bagal** [comment]
> @vitt-bagal : Releases are atomic and immutable, but I can release 1.1.7-10

Okay, Releasing new version will be helpful.

**Comment by deniszh** [comment]
@vitt-bagal : Well, looks like s390 has not all packages installed, e.g. collectd absent. Not sure how to test that properly.... Probably will temporary add it to master workflow.

**Comment by vitt-bagal** [comment]
@deniszh Before raising PR, I have verified docker image built from this repo on s390x vm and it was working fine for me.
Not sure how collectd is not getting installed here. Is it possible for you to push this newly built image(multiarch) to any temporary repo like in your dockerhub account ? I can cross verify it again by pulling it.

**Comment by deniszh** [comment]
I can't push image because it was not built. -
https://pkgs.alpinelinux.org/packages?name=collectd&branch=v3.13t's because
of latest alpine, collectd is absent there -
https://pkgs.alpinelinux.org/packages?name=collectd&branch=v3.13
but no worries, I'm testing fix already.

пн, 22 февр. 2021 г. в 12:01, vitt-bagal <notifications@github.com>:

**Comment by deniszh** [comment]
released 1.1.7-11, building now. Please note that go-carbon also crashing
during build, disabled it for s390x

пн, 22 февр. 2021 г. в 13:01, Denis Zhdanov <denis.zhdanov@gmail.com>:

**Pull request merged**
