### PR TITLE
Smaller baseimage with Alpine

### LINKED ISSUE #55: Add an Alpine Linux variant
Alpine-based images are typically much smaller than Debian-based ones.

### PR DESCRIPTION
**Pull request by bebehei**
It builds fine, but I'm currently testing it on my machine. But I'm not considering it mergable yet.

----

This gets rid of the phusion image and uses Alpine as the base. You don't have to care about security updates anymore, as these are included in Alpine.

Also it's possible to build it on aarch64 (and probably on all other docker supported archs, too). Also it builds much faster on my Odroid C2 (about 1/3 of the time).

This reduces the image size dramatically from ~530MB to 188MB.

Fixes #55 

---

I've got a question: Why did you install NodeJS 6 in the image? Is it because statsd's latest release is from 2016 and NodeJS 6 then was the latest version? I don't find any notice in the commits.

### CODE REVIEW

**Comment by piotr1212** [comment]
> I've got a question: Why did you install NodeJS 6 in the image? Is it because statsd's latest release is from 2016 and NodeJS 6 then was the latest version? I don't find any notice in the commits.

Guess so, latest statsd 'release' doesn't work with newest nodejs. There are some patches in master which fix compatibility. I'm using https://github.com/etsy/statsd/archive/8d5363cb109cc6363661a1d5813e0b96787c4411.tar.gz#/statsd-8d5363c.tar.gz in the Fedora packages.

**Comment by deniszh** [comment]
Yes, what @piotr1212 said. We can use newer NodeJS with a patch then.

**Comment by deniszh** [comment]
But much appreciated, @bebehei , I had this idea to do the same, but I'm a bit busy recently. Thanks!

**Comment by bebehei** [comment]
Ok, statsd seems to be running now properly with the given NodeJS version. Thanks @piotr1212

**Comment by bebehei** [comment]
Well, graphite web and graphite do work properly.

Redis, statsd and collectd do start, too. But I'm not sure, if they're still properly configured. I don't use them, so I can't judge, if they're still running properly.

But for the rest, it seems to work flawlessly.

**Comment by bebehei** [comment]
@deniszh I'd love to get a review for this code. I know it's a lot. Take your time. But at the current point, I myself consider my work on this PR as "finished" (of course except for fixes of upcoming comments).

**Comment by deniszh** [comment]
Well, I already did one comment - could you please check?

**Comment by bebehei** [comment]
@deniszh Where? I don't see anything. May it be, you started a review, but didn't submit it fully?

**Comment by deniszh** [comment]
Ah, nevermind, just found out that's not relevant. Plz give me some time to properly review it, especially in corner cases. Thanks a lot!

**Comment by deniszh** [comment]
OK, change looks good, thanks, @bebehei !
Although, I'm hesitating to build 1.1.4 image with it because it's not really compatible with previous release.
So, I'm going to merge it to master branch for now and will release 1.1.5 version basing on this PR.

**Pull request merged**
